### ISSUE TITLE
Improve configurability for networknt.handler.MiddlewareHandler

### ISSUE THREAD

**Issue by pragmaticway** [networknt/light-4j#129]
I'm  using` /src/main/resources/META-INF/services/com.networknt.handler.MiddlewareHandler` configuration to setup our additional MiddleWare handlers - works just fine.

However, when I trying to do unit testing we want to substitute one of the middleware handlers defined in ` /src/main/resources/META-INF/services/com.networknt.handler.MiddlewareHandler` with a "mock" handler designed specifically for unit tests support.
So I created a new test resources file ` /src/test/resources/META-INF/services/com.networknt.handler.MiddlewareHandler` where I define a new mock handler.

Example:
`com.mock.MyMockMiddlewareHandler`

**Comment by stevehu** [comment]
The MiddlewareHandler configuration was introduced before our SingletonServiceFactory IoC so it is leveraging the Java built-in Service Provider. It is cannot be externalized like other config files based on our Config module. I will switch this to our in-house IoC service so that it can be configured with service.yml and can be externalized. Also, you can have another copy of service.yml with your mock handler in src/test/resources/config folder to testing.
