### ISSUE TITLE
[question] - grpc adoption within light4j

### ISSUE THREAD

**Issue by archenroot** [networknt/light-4j#161]
Any plans here?

**Comment by stevehu** [comment]
It is in my priority list; however, there are some concerns so I haven't dived into it. 

Disadvantages: 
1. There is an official implementation based on Netty already. 
2. Protobuf is not very fast for Java in general and that is why most people are using C++ or Go for gRPC.
3. Java runtime is relatively bigger than other languages.

Advantages:
1. Netty doesn't support HTTP 2.0 natively so it is very hard to use.
2. It should be really easy to replace the transport layer with light-4j from Netty.

Questions:
1. How to attract developers to use our implementation instead of the official one?
2. Do we want to support other serialization protocol? Flat Buffer? CapnProto? 
3. Do we want to expend to TCP support instead of HTTP 2.0 only?
4. Why do we want to do that if light-hybrid-4j json based on HTTP 2.0 is already very fast?

**Comment by archenroot** [comment]
@stevehu - 

Disadvantages - 2. not very fast, yeah I discovered such fact as well.


Questions - yeah, these questions more lead itself to fact that at moment it shouldn't be a priority :-)

Thanks for summary.
