### ISSUE TITLE
provide skywalking light-4j plugin

### ISSUE THREAD

**Issue by wu-sheng** [networknt/light-4j#167]
Do light-4j team have interested to provide a light-4j plugin for Apache SkyWalking APM? We have supported a lot of popular framework, and new 5.0 will be released soon.

#### Plugin Development Guide
https://github.com/apache/incubator-skywalking/blob/master/docs/en/Plugin-Development-Guide.md

#### Supported list
https://github.com/apache/incubator-skywalking/blob/master/docs/Supported-list.md

**Comment by stevehu** [comment]
@wu-sheng It is in our priority list; however, it is new to me and I have to read a lot in order to understand how to use it. Thanks a lot for the document links. I have changed title so that we can use this to track the progress.

**Comment by wu-sheng** [comment]
Take you time. After we release 5.0 alpha, will be easier to check the plugin.

**Comment by stevehu** [comment]
@wu-sheng We are actively working on the integration with the 6.x version. I have found the following instrumentation for Undertow 2.x and I think it is a good starting point as light-4j is based on the Undertow 2.x. We might also advise API developers to leverage OpenTracing API in their handlers/functions/methods to collect more details. Am I on the right track? Thanks.

https://github.com/apache/skywalking/tree/master/apm-sniffer/apm-sdk-plugin/undertow-plugins

**Comment by wu-sheng** [comment]
Hi, I recommend you to follow
1. Plugin dev doc, https://github.com/apache/skywalking/blob/master/docs/en/guides/Java-Plugin-Development-Guide.md
1. Plugin test case contribution doc, https://github.com/SkyAPMTest/agent-auto-integration-testcases/blob/master/docs/how-to-write-a-plugin-testcase.md

Those two with existing plugins as examples are a good beginning. OpenTracing, we just recommend our users use it when they want to add some spans from business codes. As light-4j is a framework library, auto-instrumentation by SkyWalking plugin would be much more friendly.

**Comment by stevehu** [comment]
@wu-sheng Thanks a lot for the quick response. Yes. Auto-instrumentation is the way to go and we will only advise our users to add additional spans for their functions/methods within the business logic. SkyWaling is very popular in China and a lot of users are asking for the integration.

**Comment by wu-sheng** [comment]
Yes, we are extending very quickly in there two years, especially after the v6 release.
We are trying to make it popular global as next step.

**Comment by tsuilouis** [comment]
@stevehu @chenyan71 I have created the two pull requests for the Light4J 1.6.x plugin:

- Plugin is at https://github.com/apache/skywalking/pull/3323
- Test cases are at https://github.com/SkyAPMTest/agent-auto-integration-testcases/pull/83

Just wanted to note that I saw that Skywalking uses Java 8 and so I wasn't sure about compatibility with Light4J 2.x which uses Java 11. That's why I focused on 1.6.x for now.

**Comment by wu-sheng** [comment]
Hi, SkyWalking is JDK 1.6 compatible in agent side. And it should work for JDK 11+ from my tests. Only one risk may be gRPC, could you try?

**Comment by wu-sheng** [comment]
Super.

**Comment by tsuilouis** [comment]
As per @chenyan71's request, I am copying over our Slack conversation starting from Sept 1, 2019 as a public record:

gavin
> I read the comment from the PR. I think probably we should create a separate handler which extend LightHttpHandler for the APM span.
if users want to use skywalking, they can extend the new handler from the business handler

stevehu
> the difference in light-4j is the middleware handler chain to separate technical concerns from business concerns. I am sure that a lot of users would like to know how many middleware handlers are invoked before their business handler(s) are executed. Given the advice from SkyWalking, I think we can make this as configurable and write down the document clearly. If the performance is the concerns, then it should be disabled. Otherwise, it can be enabled with more detailed tracing info collected. What do you think?

gavin
> but from WuSheng's comments, Skywalking more focus on business concerns
So probably we can make it as a option,  User new skywalking handler or LightHttpHandler  for the span?

stevehu
> Louis Tsui Do you know how to use Light-4j Span to override Undertow Span?

Louis Tsui
> No, but I can look at the Spring MVC annotation that Wu Sheng mentioned and I expect there should be code there that does overriding somehow. The agent I have so far never even creates an entry span, but it seems that we should have our own entry span and not reuse the Undertow plugin's. This leads to the question of where exactly this entry span should be created: the starting point should be at OrchestrationHandler?
Also, just thinking at a high level: for providing an option, I think we could have two *Interceptor classes now. The one we already have should now intercept from MiddlewareHandler instead of LightHttpHandler. Then we can create Interceptor for a SkywalkingHandler interface which extends LightHttpHandler, which is for business code to implement. This way, we should be able to easily to tell the first Interceptor to "turn off" if desired. I need to investigate if this actually makes sense with the Skywalking code.

stevehu
> From business point of view, the best place to have entry point is the business handler. As all business handlers are implementation of LightHttpHandler, I think we can have our entry span there if possible. My understanding is that all agent plugins will be started with the server or at least Undertow and Light-4j are started together, we need to let SkyWalking know that the light-4j entry span will override the Undertow one. I might be wrong as I am not familiar with how it works.

Louis Tsui
> Ok, that makes sense. One issue I see is that the class targeting mechanism that Skywalking plugins use does not fit well with what we want to do. There are a few ways to target a class as described in point 1 of https://github.com/apache/skywalking/blob/master/docs/en/guides/Java-Plugin-Development-Guide.md#implement-plugin.
Ideally, we would use the `byName` method. However, the business handler name (and package) is unknown to us since it is based off the OpenAPI spec endpoint name so we can't provide a fixed string for the class name. I don't think the `annotation` methods are relevant to us. This leaves `byHierarchyMatch` and if we use just LightHttpHandler we will end up targeting MiddlewareHandlers as well, as you saw with the current form of the plugin. ~I looked through the Skywalking code and unfortunately there doesn't seem to be the capability to exclude certain classes that inherit from a parent.~
That's why in my previous post I think we need something like
LightHttpHandler ---> MiddlewareHandler
LightHttpHandler ---> SkywalkingHandler (probably just a marker interface) ---> BusinessEndpointHandler (end user must implement SkywalkingHandler)
This way, we can specifically target the SkywalkingHandler interface with one Interceptor type. I also realized that picking this approach requires us to have this new interface in light-4j and probably means only the newest 1.6.x and 2.x versions will support the plugin, unless we apply a patch to all the previous versions.
EDIT: please ignore crossed out line. Maybe I can have logic to exclude MiddlewareHandlers using the `EnhancedInstance objInst` parameter in the Interceptor's `beforeMethod` method, something like `if (!objInst.getClass().getInterfaces()[0].equals(MiddlewareHandler.class) && !objInst.getClass().equals(OrchestrationHandler.class))`. This works, but seems pretty inelegant.

Louis Tsui
> Also, if LocalSpan creation is enabled for MiddlewareHandlers I'm not sure it will make sense to generate a chain of LocalSpans before hitting the business handler that creates an EntrySpan. According to Skywalking definitions https://github.com/apache/skywalking/blob/master/docs/en/guides/Java-Plugin-Development-Guide.md#span, the EntrySpan marks hitting a service provider/server-side endpoint. Wouldn't it be strange to see multiple EntrySpans for a single light-4j operation or many LocalSpans followed by a EntrySpan?

**Comment by tsuilouis** [comment]
I have observed that just creating another EntrySpan overwrites any previous existing ones, **if** execution is across the same thread. Otherwise I am seeing that there are two EntrySpans. From this, I believe we cannot place the EntrySpan in the business handler’s handleRequest method due to the earlier ExceptionHandler’s handleRequest async execution.

**Comment by wu-sheng** [comment]
Yes. If in async handler chain, I would recommend creating local span only.

**Comment by stevehu** [comment]
Good findings!!! Let's just leave the entry span in the ExceptionHandler then.

**Comment by wu-sheng** [comment]
> Good findings!!! Let's just leave the entry span in the ExceptionHandler then.

Why ExceptionHandler for entry span? Strange to me.

**Comment by stevehu** [comment]
@wu-sheng For each endpoint on a server, the request will pass several middleware handlers before reaching the business handler and the ExceptionHandler is the first one in the chain. Hence, it is the best location to start the entry span in my opinion. The other option is to start the entry span in the LightHttpHandler which all business handlers will be extended; however, as business handlers are implemented by the users and we cannot ensure that they are all extending from the LightHttpHandler.

**Comment by wu-sheng** [comment]
Got it, then `ExceptionHandler` makes sense to me.

**Comment by tsuilouis** [comment]
I was able to easily create an EntrySpan just before the first ExceptionHandler#handleRequest method execution. What was trickier is the scenario that Steve would like to cover: the option to create LocalSpans for all the `MiddlewareHandler`s + business handler.

I did some further experimenting and I found out that I need to have two LocalSpans created in order to maintain a single trace as it appears in the Skywalking UI. Otherwise, the UI indicates the trace has an error with a cross mark. So for the ExceptionHandler we must create a LocalSpan in the original thread and a second LocalSpan in the new non-I/O thread. This led me to check if we can create both the EntrySpan and the LocalSpan just before the first execution of the ExceptionHandler#handleRequest method and I found out that yes, we can do that.

Now I just need to make this configurable so I can create LocalSpans depending on that flag.

**Comment by wu-sheng** [comment]
>  So for the ExceptionHandler we must create a LocalSpan in the original thread and a second LocalSpan in the new non-I/O thread.

Maybe you could just create one local span, if the only reason to create the first is across-thread. Due to the entry span is always existing, you could do `#capture` only, rather than `createLocal` then `#capture`.

**Comment by tsuilouis** [comment]
@wu-sheng Thanks for all your help. I have updated my code (https://github.com/apache/skywalking/pull/3323) and automated test cases (https://github.com/SkyAPMTest/agent-auto-integration-testcases/pull/83) based on our discussions here.

**Comment by wu-sheng** [comment]
Merged, it will be included in 6.5.0 release.
