### ISSUE TITLE
Unexpected behavior when Status is created for non-existent status code

### ISSUE THREAD

**Issue by ddobrin** [networknt/light-4j#169]
Framework user reports an incorrect behavior when a Status object is created, and the status and its associated description are not found in the status.yml file

**Comment by stevehu** [comment]
There is an exception happens when the framework tries to construct a Status object from status.yml config file. What would be the best approach to handle this scenario? 

* Create another error code to indicate that a specific status code is missing from status.yml?
* Just log it as an error in the stdout and log file?

**Comment by stevehu** [comment]
A default method has been added into MiddlewareHandler interface to setExchangeStatus. If the status code is not loaded successfully from status.yml file, then an ERROR_NOT_DEFINED will be returned. 

```
    default void setExchangeStatus(HttpServerExchange exchange, String code, final Object... args) {
        Status status = new Status(code, args);
        if(status.getStatusCode() == 0) {
            // There is no entry in status.yml for this particular error code.
            status = new Status(ERROR_NOT_DEFINED, code);
        }
        exchange.setStatusCode(status.getStatusCode());
        exchange.getResponseSender().send(status.toString());
        logger.error(status.toString());
    }
```
