### ISSUE TITLE
Decryptor problem with AES-GCM

### ISSUE THREAD

**Issue by AdrianGDuarte** [networknt/light-4j#1825]
Hi, I hope my message finds you well.

I'm currently having some problems when updating Ligh4J from version 2.1.9 to a newer one. I'm encrypting my passwords using AES-GSM(256), but I'm no longer able to decrypt them. I've checked the past PRs and I saw this one: https://github.com/networknt/light-4j/pull/1687
The regex to mark a string as a CRYPT changed and my passwords don't match it anymore (special characters are gone, for instance). As far as I know, AES-GCM doesn't use salt, but initialization vectors. However, it's true that I'm not an expert in cryptography. My question here is about the fact that we can't use our own decryptors as they were before. Should we change our encryption?

Thank you very much and best regards.

**Comment by stevehu** [comment]
@AdrianGDuarte Yes. In the newer version, we have removed AESDecryptor as many users are using it, which is unsafe. It was a reference implementation to showcase how to implement customized Decryptor, but many users don't want to implement their own. To address this security vulnerability, we have to remove it and replace it with a safe implementation AESSaltDecryptor. 

Also, the Config module is updated to automatically load the decryptor from the startup.yml (built-in) so you don't need to have the Decryptor interface and implementation defined in the service.yml anymore. 

What you need to do is to re-encryptor your secret with https://github.com/networknt/light-encryptor repo. You need to choose your own password for encryption and pass the password as an environment variable to the light-4j instance. 

Let me know if you have any questions. Thanks.

**Comment by AdrianGDuarte** [comment]
@stevehu thank you very much for your reply.

However, there's still something I don't fully understand: can we still use our own Decryptor implementation or is it mandatory to use the built-in one?

Thanks!

**Comment by ForwardKeys** [comment]
Hi @stevehu , we've been impacted by this change as well. In our case, we were using our own decryptor, so it's a relief reading that we can keep using it. However, with the regex mentioned by @AdrianGDuarte, our own decryptor no longer works. 
Is there a way to use a customised regex for that case, something that could be parametrized from a config file? We understand the rationale behind the commit [,](https://github.com/networknt/light-4j/pull/1687)  but also changing the encryption system from one version to the other is probably too tough for many Light4j users (including ourselves). Allowing us to keep the previous regex, even if not secure as should be, would allow us to jump into a better encryption system in the future, without forcing us to be stuck on an older version of Light4j until the required changes are applied.

**Comment by stevehu** [comment]
@ForwardKeys and @AdrianGDuarte I am guessing your encryptor and decryptor using a different format that is not passing the regex validation, which starts with CRYPT. At the moment, I don't see the changes for the String validation, and both the new format and the old format are the same in the generated secret. I am wondering if you could elaborate a little bit more or pin point the problematic line of code. We can resolve the issue easily if I understand it. Thanks.

**Comment by ForwardKeys** [comment]
Sorry @stevehu, I didn't explain myself. Prior to the commit in [1687](https://github.com/networknt/light-4j/pull/1687), the regex was:
` public static final Pattern CRYPT_PATTERN = Pattern.compile("^CRYPT:([A-Za-z0-9+/]{4})*([A-Za-z0-9+/]{4}|[A-Za-z0-9+/]{3}=|[A-Za-z0-9+/]{2}==)?$");   	`
However, after that commit, the pattern is now:
` public static final Pattern CRYPT_PATTERN = Pattern.compile("CRYPT:[a-f0-9]+:[a-f0-9]+");`
The new CRYPT regex expects a salt, and also the allowed values are more restrictive. That change has rendered all of our passwords invalid, because the customised decryptor we were using has adapted to that regex. That's why we were asking if there is any way of using the old regex pattern, like allowing a config file to set a customised one, so we can use the former pattern. 
Changing all of the encrypted passwords in production environment to be adjusted to this new regex pattern would be delicate and time consuming.

**Comment by stevehu** [comment]
@ForwardKeys @AdrianGDuarte Could you please review the PR and let me know if this should work for your use case?

**Comment by ForwardKeys** [comment]
Much appreciated @stevehu, it will indeed fix it
