### ISSUE TITLE
Mapped Diagnostic Context (MDC) is not working if request is cross multiple threads

### ISSUE THREAD

**Issue by stevehu** [networknt/light-4j#193]
https://logback.qos.ch/manual/mdc.html
http://www.baeldung.com/mdc-in-log4j-2-logback

**Comment by ddobrin** [comment]
The issue is not only setting it once, but also unsetting at the end of the execution, especially if it is on a new thread.

One small improvement is the clearing of the MDC context in the exception handler, not in the finally block, but the request side, which will clear the MDC context at the start of that invocation chain.

**Comment by stevehu** [comment]
http://shengwangi.blogspot.ca/2015/09/using-log-mdc-in-multi-thread-helloworld-example.html

A good example above when you are using executor explicitly. We need to find the right location to inject the MDC in Undertow.

**Comment by stevehu** [comment]
https://stackoverflow.com/questions/6073019/how-to-use-mdc-with-thread-pools

Another good article.
