### ISSUE TITLE
A default content-type is not set

### ISSUE THREAD

**Issue by rpinaa** [networknt/light-4j#216]
When I started using the rest archetype of Light-4j, when an error is throwing or any specific feature returns something, there isn't a default RESPONSE content-type from the server; or perhaps I'm not setting a default content-type for all the ecosystem. Is there a place where I can apply this?

**Comment by rpinaa** [comment]
I have implemented a middleware called ContentTypeHandler as follow:

ContentTypeConfig

public class ContentTypeConfig {

  boolean enabled;

  String defaultContentType;

  @JsonIgnore
  String description;

  public ContentTypeConfig() { }

  public boolean isEnabled() {
    return enabled;
  }

  public void setEnabled(boolean enabled) {
    this.enabled = enabled;
  }

  public String getDefaultContentType() {
    return defaultContentType;
  }

  public void setDefaultContentType(String defaultContentType) {
    this.defaultContentType = defaultContentType;
  }

  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }
}

ContentTypeHandler

public class ContentTypeHandler implements MiddlewareHandler {

  public static final String CONFIG_NAME = "content";

  public static final ContentTypeConfig config = (ContentTypeConfig) Config.getInstance().getJsonObjectConfig(CONFIG_NAME, ContentTypeConfig.class);

  private static final String defaultContentType = config.getDefaultContentType();

  private volatile HttpHandler next;

  public ContentTypeHandler() {

  }

  @Override
  public HttpHandler getNext() {
    return next;
  }

  @Override
  public MiddlewareHandler setNext(final HttpHandler next) {

    Handlers.handlerNotNull(next);

    this.next = next;

    return this;
  }

  @Override
  public boolean isEnabled() {
    return config.isEnabled();
  }

  @Override
  public void register() {
    ModuleRegistry.registerModule(ContentTypeConfig.class.getName(), Config.getInstance().getJsonMapConfigNoCache(CONFIG_NAME), null);
  }

  @Override
  public void handleRequest(final HttpServerExchange exchange) throws Exception {
    if (exchange.getRequestHeaders().contains(Headers.CONTENT_TYPE)) {
      exchange
        .getResponseHeaders()
        .put(Headers.CONTENT_TYPE, exchange
          .getRequestHeaders()
          .get(Headers.CONTENT_TYPE).element());
    } else {
      exchange
        .getResponseHeaders()
        .put(Headers.CONTENT_TYPE, defaultContentType);
    }

    next.handleRequest(exchange);
  }
}

content.yml

---
description: Default Content Type
enabled: true

defaultContentType: application/json

**Comment by rpinaa** [comment]
It's really working for me, but I don't know if there is a better approach. Thanks

**Comment by stevehu** [comment]
@rpinaa Nice catch! Internally, we have an assumption that all error messages are in JSON format by default as our status module serializes to JSON only. I agree with you that we should have this content type set explicitly. Your implementation is one of the options and it should work gracefully. The other option is the update the MiddlewareHandler.java in handler module for the default method. You approach is more generic and won't be missed once it is wired in the request/response chain. The default method needs to be used for all middleware handlers in order to be working. Could you please create a pull request on the develop branch to add your handler? In this case, we can let users choose which one to use. Thanks.

```
    default void setExchangeStatus(HttpServerExchange exchange, String code, final Object... args) {
        Status status = new Status(code, args);
        if(status.getStatusCode() == 0) {
            // There is no entry in status.yml for this particular error code.
            status = new Status(ERROR_NOT_DEFINED, code);
        }
        exchange.setStatusCode(status.getStatusCode());
        exchange.getResponseHeaders().put(Headers.CONTENT_TYPE, "application/json");
        exchange.getResponseSender().send(status.toString());
        logger.error(status.toString());
    }
```

**Comment by rpinaa** [comment]
Yeah, I have seen the commit to fix it, so I'm continue testing the features and waiting for the release. Thanks.

**Comment by rpinaa** [comment]
@stevehu I have created the pull request, but I was thinking about /health handler; this is sending just a text/plain object "OK", others /health return something like { status: 'OK' } as a JSON format. I suppose /health handler is gonna has problems with the "application/json" Content-Type, isn't it?

**Comment by stevehu** [comment]
The health endpoint normally used by other monitoring tools including F5. It is good to just return text/plain as some tools won't support JSON parsing at all. We are working on another POC to support multiple chains so that we can move health to another chain without security etc. I think the best way for the content handler is to set the header in the response chain if the content type is empty.
