### ISSUE TITLE
metrics-config is failing the Maven building using jdk21

### ISSUE THREAD

**Issue by mihai-vladuc** [networknt/light-4j#2362]
We'd like to upgrade our project to JDK21 but the Maven unit test build errors are preventing that.
 
Light4J Tag :
 light-4j git:(2.1.37) 

Java version used:
Java version "21.0.4" 2024-07-16 LTS
Java(TM) SE Runtime Environment (build 21.0.4+8-LTS-274)
Java HotSpot(TM) 64-Bit Server VM (build 21.0.4+8-LTS-274, mixed mode, sharing)

Maven Build Error:

[ERROR] Failures: 
[ERROR]   ConsoleReporterTest.reportsCounterValues:102 expected:<"3/17/13, 6:04:36[ ]PM =================...> but was:<"3/17/13, 6:04:36[ ]PM =================...>
[ERROR]   ConsoleReporterTest.reportsGaugeValues:79 expected:<"3/17/13, 6:04:36[ ]PM =================...> but was:<"3/17/13, 6:04:36[ ]PM =================...>
[ERROR]   ConsoleReporterTest.reportsHistogramValues:139 expected:<"3/17/13, 6:04:36[ ]PM =================...> but was:<"3/17/13, 6:04:36[ ]PM =================...>
[ERROR]   ConsoleReporterTest.reportsMeterValues:176 expected:<"3/17/13, 6:04:36[ ]PM =================...> but was:<"3/17/13, 6:04:36[ ]PM =================...>
[ERROR]   ConsoleReporterTest.reportsTimerValues:222 expected:<"3/17/13, 6:04:36[ ]PM =================...> but was:<"3/17/13, 6:04:36[ ]PM =================...>
[INFO] 
[ERROR] Tests run: 238, Failures: 5, Errors: 0, Skipped: 0

[INFO] metrics-config ..................................... FAILURE [  4.218 s]

**Comment by stevehu** [comment]
I have reproduced the issue and I am working on it. Thanks for reporting it.

**Comment by miklish** [comment]
Hi @stevehu 
I'm a bit worried about this solution (to ignore the failing tests). Do you have any indication of why these tests pass under JDK11 and JDK17 but fail in JDK21? My concern is that this is an indication of some deeper incompatibility

**Comment by stevehu** [comment]
The test case failed due to the Powermock is not compatible with Java 21. Another issue with the ldap util is due to the test apache LDAP server doesn't work with Java 21. It hung during the init context with directory-based LDAP.  It works if you run it in the IDE though. I am guessing there are some timing issues but need more debugging. Thanks.

**Comment by stevehu** [comment]
Here is the official document site for the Apache directory server and it supports Java 11 and Java 17. Java 21 is not supported. So our only option is to disable the test case if users want to build the light-4j with Java 21. Currently, we release light-4j jars with Java 11 in order to make sure that more Java base images can use the jar. We have tested with Java 11, 17, and 21 for http-sidecar and light-gateway. We are releasing snapshot version very frequently these days, may I know why you compile light-4j with Java 21? Thanks.

**Comment by miklish** [comment]
Hi @stevehu , thanks for looking into this. Your explanation makes sense.

As for JDK21: One reason we are looking at JDK21 because it currently has a longer official support Window than JDK17. Also -- in general -- we want to improve our JDK currency and ensure our applications work with the latest VMs (as well as earlier VMs). We got a bit stuck on JDK8 and do not want to repeat that.

We are still restricting our bytecode to Java 11 however.

Thanks again

**Comment by stevehu** [comment]
It makes perfect sense to go with jdk21 at the moment; however, we have to consider different teams will move at different times in a big organization. To be on the safe side, we are still releasing binary jars in Java 11. There are teams using jdk11, 17, and 21 with java11 binary these days.
