### ISSUE TITLE
Provide a handle to set connection timeout on ClientConnection object

### ISSUE THREAD

**Issue by jay-flipsyd** [networknt/light-4j#240]
The light4j library’s Http2Client uses non-blocking socketChannel but it doesn’t seem to have a connection time-out configured.
 
```
connection = client.connect(new URI(apiHost), Http2Client.WORKER, Http2Client.SSL, Http2Client.POOL, APIProtocol.equalsIgnoreCase(PROTOCOL_H2) ? OptionMap.create(UndertowOptions.ENABLE_HTTP2, true): OptionMap.EMPTY).get();
```
 
The connection.sendRequest can be wrapped in a Latch to set a read timeout.
 
connection.sendRequest(request, client.createClientCallback(reference, latch, requestBody));
boolean responseReceived = latch.await(timeout, TimeUnit.SECONDS);
 
The non-blocking setting allows an asynchronous way to connect and read/write separately, however, we should have a finite interval to stop trying to establish a connection to a rest service (getting a connection object).
 
The internal class socketChannel allows to set socket timeout; however, there is no direct handle to it. Please share your views and any available information.
 
FY Reference:
http://www.java-gaming.org/index.php?topic=17250.0
https://community.oracle.com/thread/1145435

**Comment by stevehu** [comment]
@jay-flipsyd I have read the reference links but there is no clear answer on how this can be done gracefully. Do you have an idea on how this should be implemented? Thanks.

**Comment by jefperito** [comment]
i can not figure out a good solution without do some trade offs, so In my solution we need to refactor the whole methods from Http2Client that returns IoFuture<ClientConnection> to a wrapper, e.g.:

`java   
public ClientTimeoutConnection connect(final URI uri, final XnioWorker worker, ByteBufferPool bufferPool, OptionMap options) throws IOException {
        return new ClientTimeoutConnection(connect(uri, worker, null, bufferPool, options).get());
}`

Wrapper sketch:

`java
public final class ClientTimeoutConnection {

    private final ClientConnection clientConnection;

    public ClientTimeoutConnection(ClientConnection clientConnection) {
        this.clientConnection = clientConnection;
    }

    public void sendRequest(ClientRequest clientRequest, Http2Client client, AtomicReference<ClientResponse> reference) throws InterruptedException {
        CountDownLatch latch = new CountDownLatch(1);
        clientConnection.sendRequest(clientRequest, client.createClientCallback(reference, latch));

        if (!latch.await(1, TimeUnit.MILLISECONDS)) {
            throw new IllegalStateException("Connection timeout!");
        }

    // code that doesnt matter
    }
`

time unit/amount of time should be loaded from config file and thinking about circuit breaker [#241](https://github.com/networknt/light-4j/issues/241) instead of throws a exception, uses a callback/hook or just to return latch.await's return.

**Comment by jefperito** [comment]
i can not figure out a good solution without do some trade offs, so In my solution we need to refactor the whole methods from Http2Client that returns IoFuture<ClientConnection> to a wrapper, e.g.:

```java   
public ClientTimeoutConnection connect(final URI uri, final XnioWorker worker, ByteBufferPool bufferPool, OptionMap options) throws IOException {
        return new ClientTimeoutConnection(connect(uri, worker, null, bufferPool, options).get());
}
```

Wrapper sketch:

```java
public final class ClientTimeoutConnection {

    private final ClientConnection clientConnection;

    public ClientTimeoutConnection(ClientConnection clientConnection) {
        this.clientConnection = clientConnection;
    }

    public void sendRequest(ClientRequest clientRequest, Http2Client client, AtomicReference<ClientResponse> reference) throws InterruptedException {
        CountDownLatch latch = new CountDownLatch(1);
        clientConnection.sendRequest(clientRequest, client.createClientCallback(reference, latch));

        if (!latch.await(1, TimeUnit.MILLISECONDS)) {
            throw new IllegalStateException("Connection timeout!");
        }

    // code that doesnt matter
    }
```

time unit/amount of time should be loaded from config file and thinking about circuit breaker [#241](https://github.com/networknt/light-4j/issues/241) instead of throws a exception, uses a callback/hook or just to return latch.await's return.

**Comment by stevehu** [comment]
@jefperito @chenyan71 has created a new branch to introduce the async client and it is the other side of the coins for this timeout and async issue. I personally working on another repository with Kotlin coroutines and it resolves the issue gracefully. 

https://github.com/networknt/light-4j/tree/async_client

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [timeout feature #241 circuit breaker](https://trello.com/c/jlrsQrEQ/182-timeout-feature-241-circuit-breaker)
