### ISSUE TITLE
Feedback request to change interface of handler.yml to support multi-path/multi-method combinations

### ISSUE THREAD

**Issue by NicholasAzar** [networknt/light-4j#249]
Current interface is designed such that each path in the path list defines a single target url with a single http method (as follows):
```yaml
- path: /v1/health
  method: get
  exec:
      - unsecured
      - health
```

In order to support more terse configurations, we could support multiple items in the path field (changing name to paths), and multiple items in the method field (methods):

```yaml
- paths: 
      - /v1/health
      - /v2/health
  methods:
      - get
      - post
  exec:
      - unsecured
      - health
```

In which case both paths would support both get and post methods (cartesian product).

Any feedback for this would be greatly appreciated.

From: https://gitter.im/networknt/light-4j?at=5b647baba9426c705d210ebc

**Comment by NicholasAzar** [comment]
Paging @stevehu @ddobrin @miklish

**Comment by stevehu** [comment]
I think this is a good idea. It makes the definition more efficient. Since the API is not stabilized yet, it is the good time to make the change. @ddobrin and @logi what do you think? You are the most impacted. Thanks.

**Comment by ddobrin** [comment]
I thinks this could be useful, maybe combine health and server info for brevity under 1 declaration, for ex. 

Now, there are a number of items to be addressed, as listed under #247

I would like for us to:
- **close #247 first**, as it changes 2 or more classes, as well as the status.yml 
- document the interface for the handler.yml
   - for ex, for legibility, I'd prefer - health: com.networknt.health.HealthGetHandler to the existing
                                                        - com.networknt.health.HealthGetHandler@health
- only then make the change for a simplified set of paths.

How does this sound?

**Comment by ddobrin** [comment]
To add to the concern of impact, all APIs in my current project need a certain refactoring after the next light-4j release, therefore the changes will be made if necessary.

After this effort, the interface to the handler.yml needs to be remain backwards compatible

**Comment by stevehu** [comment]
@ddobrin As you have the most APIs implemented, we really need your input to ensure we take the best approach. It would be very hard to make changes down the road. Thanks.

**Comment by ddobrin** [comment]
Logi,
right now they are mutually exclusive; either the backwards compatible mechanism using service.yml or the newer handler.yml.

In the first, you are not specifying the routing handlers, however in the newer one you do.

This will be rationalized

**Comment by stevehu** [comment]
Do you guys think it is too much work to make it backward compatible? If that is the case, we can break it this time and bump up the version to 1.6.0. Most existing APIs will migrate anyway and the new implementation of the Consul support health check to /health from the agent actively. If users want to leverage the Consul HTTP health check, then it makes sense to have /health exposed instead of /v1/health. Server info is in the same situation and it would be better to standardize the path so that it would be much easier to integrate with the API certification in the portal.

**Comment by ddobrin** [comment]
#247 is fixed; it addresses the feedback provided in this Issue.

Changes include:

- /handler and /serverInfo are used
- MiddlewareHandler interface is leveraged in both cases; the handlers can be disabled via the enabled flag in the respective middleware handler configuration
- different failures issue a finer granular indication of where the config has failed

The document for handler usage, with a sample config, will be updated separately.

**Comment by logi** [comment]
Right now this is what I'd most like to see
```yaml
path_generators:
- type: ...OpenApiPathGenerator
  spec: .../myapi/openapi.json
  exec:
    openapi-chain  # Defined above
    myapi-hander  # Defined above
- type: ...OpenApiPathGenerator
  spec: .../otherapi/openapi.json
  exec:
    opneapi-chain  # Potentiatlly a different chain but usually the same
    otherapi-handler  # Defined above
- type: ...GraphqlPathGenerator
  exec:
    graphql-chain
    graphql-handler  # Or it could be in the chain. That's up to the deployer.
```

**Comment by stevehu** [comment]
@logi I think I understand what you mean; however, I think makes startup more complicated and less clear for normal developers. With the latest light-codegen, the paths are all generated in handler.yml config file and users can clearly see how each path is handled and they can be customized individually.  What we can do is to give an option to set up a default path and reuse the PathHandlerProvider. 

```
paths:
  - path: '/health/com.networknt.petstore-1.0.1@get'
    exec:
      - health
  - path: '/server/info@get'
    exec:
      - info
  - path: '/publicapi/api/v2/*'
    exec:
      - default
      - com.networknt.petstore.handler.PathHandlerProvider

```

I don't know if this is a good idea as the mapping between paths and handlers are scattered in two different files. What do you think?

**Comment by stevehu** [comment]
It can be even simplified as

```
paths:
  - path: '/health/com.networknt.petstore-1.0.1@get':
      - health
  - path: '/server/info@get':
      - info
  - path: '/publicapi/api/v2/*':
      - default
      - com.networknt.petstore.handler.PathHandlerProvider
```

**Comment by logi** [comment]
Prefix mapping would make the configuration much lighter and was what I was leaning towards until I realised that then the parameter names in e.g. `/publicapi/api/v2/frobnitz/{frobnitzId}/wobble/{wobbleId}` aren't available to the pattern matching code in undertow so the Exchange's query parameters can't be populated.

Quoting @NicholasAzar on gitter:
> ...just fyi the handler takes that parameter name by however it's defined in that handler.yml, so you'll want to set it up like - path: /notes/{noteId} and give that a try.

**Comment by stevehu** [comment]
Yes. There are a lot of details that need to be thought over before making any final design decisions. There are several things that clarified after an internal discussion. 

1. It is good we have only one location to define the path and handler mapping. That means we have to discard the PathHandlerProvider. 
2. The definition must be clear and easy to understand and easy to be modified. That means using a generator during startup might not be a good idea. 
3. There might be some improvements available for the current handler.yml but most of them are not material. With the assistant of the light-codegen, the final handler.yml is not bad even with too many endpoints. 

Based on the above points, I think we have to stay on the current design for now until we find a good reason to improve it. We will keep this issue open so that good ideas can still flow in.

**Comment by NicholasAzar** [comment]
@stevehu @logi 

There certainly have been some good ideas so far, and no doubt room for improvement in the current design.

I like the idea of only needing to define paths in the `openapi` spec. However that does add some complexity... like how we will need a way of mapping the paths in the spec to a handler chain. Could `operationId` be used in this case? This way we wouldn't need to define the http method either, however in the spec it is suppose to be unique per operation... Maybe tags can be used instead? 
https://swagger.io/docs/specification/grouping-operations-with-tags/

Building off of @logi 's above example, it could look like:
```yaml
paths:
- type: ...OpenApiPathGenerator
  operation: myEndpoint
  exec:
    openapi-chain  # Defined above
    myapi-hander  # Defined above
- type: ...OpenApiPathGenerator
  operation: myOtherEndpoint
  exec:
    openapi-chain  # Defined above
    myotherapi-hander  # Defined above
- type: ...GraphqlPathGenerator
  exec:
    graphql-chain
    graphql-handler  # Or it could be in the chain. That's up to the deployer.
```

I removed the spec path as i didn't know if we would ever have a single API with multiple spec files... Is it a valid use case?

**Comment by ddobrin** [comment]
I do not think that there will be an API which deviates from the 1:1 mapping of spec:microservice

**Comment by logi** [comment]
I'd definitely want to refine my proposed config syntax to be less jarring, so it could look something like:
```yaml
paths:
- path: /graphql
  exec:
  - graphql-chain
  - graphql-handler
- generator: ...OpenApiGenerator
  spec: ...openapi.json
  exec:
  - openapi-chain
  - my-api-handler
```

I'm still pondering the other aspects. But basically since one has to maintain a very explicit `openapi.json` file I would prefer as little duplication of that as possible. As Steve says, it's best to have a single place mapping things to things, but we're stuck with the spec file.

One half-formed thought is a handler at the end of the chain which also looks at the spec and uses either the `operationId` or rewrite rules to map request path+method to a handler class or method. Then a change to the API could be as simple as adding a `PUT` operation to an existing endpoint in the openapi.json file and then implementing the corresponding `handlePut` method. But that whole mechanism can be entirely optional and pluggable as long as there is a way to get the requests routed to that handler.

**Comment by stevehu** [comment]
We have several projects that use the handler.yml and the general responses are good. Let's keep it this way until we have further requirements. Close this issue for now. Thanks.

**Comment by logi** [comment]
After hacking around a bit I can be much more clear about why I'm so interested in being able to programmatically inject paths (or more precisely endpoints) in `handler.yml`.

I want to be able to write an `openapi.json` spec, where all endpoints are spelled out in extreme detail, and then be able to locate idiomatic java (or kotlin) code for implementing those endpoints with arguments converted to the suitable java types, request bodies parsed into carrier classes and responses serialised to JSON.

I'm a good part of the way there with a Handler which on startup iterates through `OpenApiHelper.openApi3.paths` and for e.g. endpoints `/notes` and `/notes/{noteId}` would find the methods of this class `NotesResource` in a configured root package for implementing the usual set of actions:

```java
public class NotesResource {
    public void search() {}
    public Note post(Note note) { return new Note(...); }
    public Note get(String noteId) { return new Note(...); }
    public Note put(String noteId) { return new Note(...); }
    public void delete(String noteId) {}
}
```
Those conventions are taken from the `connexion` framework which I've used extensively with Flask and python.

It would also happily use static methods or this Kotlin code (with or without an enclosing class or final keywords):
```kotlin
fun search(): List<Note> { return listOf(NOTE) }
fun post(Note note) { }
fun get(noteId: String): Note { return NOTE }
fun put(noteId: String, Note note): Note { return NOTE }
fun delete(noteId: String) { }
```

For the first `get` function it would also accept `Resource.getNote()`, `handler.Resource.get()` and if the endpoint were `/note/{noteId}/section/{sectionId}@get` It would accept any of `Resource.getNoteSection()`, `NoteResource.getSection()`, `NoteSectionResource.get()`, `note.SectionResource.get()`, `note.Resource.getSection()`, `note.section.Resource.get()` (plus all of those with `Kt` appended to the class name to support kotlin functions outside any classe) and I may have missed some. Basically the programmer can group the implementing code as they like. If no handler is found for a particular endpoint then startup fails and we helpfully log all the possible places to implement the function like so:
```
17:49:29.550 [main]   ERROR is.thing.rest.DelegatingRestHandler locateTarget - No handler found for /note/{noteId}/section/{sectionId}@get Implement one of these:
17:49:29.552 [main]   ERROR is.thing.rest.DelegatingRestHandler locateTarget -   is.thing.rest.test.note.section.Resource.get(noteId, sectionId)
17:49:29.552 [main]   ERROR is.thing.rest.DelegatingRestHandler locateTarget -   is.thing.rest.test.note.section.ResourceKt.get(noteId, sectionId)
17:49:29.552 [main]   ERROR is.thing.rest.DelegatingRestHandler locateTarget -   is.thing.rest.test.note.SectionResource.get(noteId, sectionId)
17:49:29.553 [main]   ERROR is.thing.rest.DelegatingRestHandler locateTarget -   is.thing.rest.test.note.SectionResourceKt.get(noteId, sectionId)
17:49:29.553 [main]   ERROR is.thing.rest.DelegatingRestHandler locateTarget -   is.thing.rest.test.NoteSectionResource.get(noteId, sectionId)
17:49:29.553 [main]   ERROR is.thing.rest.DelegatingRestHandler locateTarget -   is.thing.rest.test.NoteSectionResourceKt.get(noteId, sectionId)
17:49:29.554 [main]   ERROR is.thing.rest.DelegatingRestHandler locateTarget -   is.thing.rest.test.note.Resource.getSection(noteId, sectionId)
17:49:29.554 [main]   ERROR is.thing.rest.DelegatingRestHandler locateTarget -   is.thing.rest.test.note.ResourceKt.getSection(noteId, sectionId)
17:49:29.554 [main]   ERROR is.thing.rest.DelegatingRestHandler locateTarget -   is.thing.rest.test.NoteResource.getSection(noteId, sectionId)
17:49:29.555 [main]   ERROR is.thing.rest.DelegatingRestHandler locateTarget -   is.thing.rest.test.NoteResourceKt.getSection(noteId, sectionId)
17:49:29.555 [main]   ERROR is.thing.rest.DelegatingRestHandler locateTarget -   is.thing.rest.test.Resource.getNoteSection(noteId, sectionId)
17:49:29.555 [main]   ERROR is.thing.rest.DelegatingRestHandler locateTarget -   is.thing.rest.test.ResourceKt.getNoteSection(noteId, sectionId)
```

I have this working if all arguments and all results are strings and if there are no request bodies, and I've verified that all the information needed to build a list of parameter and result converters for each `EndpointTarget` (to distinguish from Handler) based on the spec and on annotated carrier classes that are ready for `objectMapper.readValue`. So that is Just Work and I don't see any significant obstacles.

However, and this is where we get back to `handler.yml`, each of the endpoints from `openapi.json` would still have to be listed in `handler.yml` with an identical `exec` chain which breaks this flow. Without having to edit `handler.yml` the workflow for openapi would be very similar to that for graphql where you edit the spec and update the java code and don't touch any other configuration.

So I propose a further simplified version of what I called a `PathGenerator` above. Instead define an interface `EndpointSource` with one method which returns an `Iterable<Endpoint>` where `Endpoint` is a pair of `String path` and `String method`, so if this sort of item is encountered in the `paths` array, the source is invoked and the result is injected at that point as if it had been read from the file with the given `exec` part:
```yaml
paths:
- path: /some/path
  exec:
  - some-chain
- source: fully.quallified.name.of.EndpointSourceImpl
  exec:
  - my-openapi-chain
  - my-delegating-openapi-handler
```

Then implement an `OpenApiEndpointSource` which iterates through the paths and methods from `OpenApiHelper.openApi.3.paths` and returns them. _Et voilà_ the `handler.yml` file for OpenAPI implementations shrinks massively by removing repetition from the `openapi.json` file and the developer workflow is much smoother. See also DRY principle.

I'm writing the first part of all this now and we'll happily donate it to the project when it's reached a usable state. I could also implement the `EndpointSource` logic if there is agreement in principle that it would be merged. The actual `OpenApiEndpointSource` is trivial.

**Comment by stevehu** [comment]
@logi I have read your last post several times to ensure I understand the details. I like the idea. This gives us the best of both worlds. For the paths that defined in the openapi.yaml or openapi.json, they are handled altogether. The handler.yml still give us a chance to define /health, /server/info and static content path. @NicholasAzar @ddobrin What do you think? Thanks.

**Comment by logi** [comment]
@stevehu Yes, that's the idea. And those who prefer to do so can still list all the OpenApi paths in `handler.yml` and specify individual handler classes for each as if nothing had happened.

**Comment by stevehu** [comment]
@logi Would you be able to submit a pull request to the develop branch? We can update the light-codegen to support both and let users choose which one to use in config.json. As so many services are using handler.yml in the current format, let's make sure it is backward compatible so that no code change for the existing APIs. Thanks.

**Comment by logi** [comment]
Will do. I expect to get to it tomorrow.

**Comment by stevehu** [comment]
I think we have implemented all the features we have discussed here. Close it.
