### ISSUE TITLE
Environment variable references in the light-4j yaml config files

### ISSUE THREAD

**Issue by pragmaticway** [networknt/light-4j#321]
This is enhancement request to create a "preprocessor" for yaml configuration files to be able to inject environment variables.

Proposed implementation specification:
--------------------------------------------
You can use environment variable references in the config file to set values that need to be configurable during deployment. To do this, use:

`${VAR}`

Where VAR is the name of the environment variable.

Each variable reference is replaced at startup by the value of the environment variable. The replacement is case-sensitive and occurs before the YAML file is parsed. References to undefined variables are replaced by empty strings unless you specify a default value or custom error text.

To specify a default value, use:

`${VAR:default_value}`
Where default_value is the value to use if the environment variable is undefined.

To specify custom error text, use:

`${VAR:?error_text}`

Where error_text is custom text that will be prepended to the error message if the environment variable cannot be expanded.

If you need to use a literal ${ in your configuration file then you can write `$${` to escape the expansion.

**Comment by NicholasAzar** [comment]
Will take a look, this is a very interesting proposition.

**Comment by ddobrin** [comment]
I would like to add a suggestion to this issue, within an existing module. 

I am discussing the following approach with my current client, and they are preparing a file with the environment variables they wish to override as an API moves across test phases. 

- the Config module loads the configuration for each individual module
- at the time of the loading of the config, an environment variable resolution process can kick in (as per @pragmaticway )
- the APIs are loading the configuration from a single location, the externalized folder (Config.java L.279). The file with the customizations can either be loaded from a set file (say env_vars.yml) within the same folder or the Config module can be expanded to allow different folders for config loading, similar to the approach we have used in (https://github.com/networknt/light-bot). 
- the customized file can be served via config-server
-  if the externalized file is present, {vars} can be resolved, with defaults or not, etc

@stevehu @NicholasAzar @pragmaticway : what do you think?

**Comment by miklish** [comment]
Much interest, research, and development time has been spent on the configuration issue recently. David is looking into possible config server enhancements and I have been developing a similar config-value injection tool myself. We should have a design session to ensure what results is a single coherent, integrated approach and not a loose collection of tools that may or may not perform the same functions

**Comment by ddobrin** [comment]
@miklish : how do you propose that we go about this session?
I need to put a process in place in the next 1-2 weeks for it, for 2 separate initiatives.

There have been a number of configuration mishaps at a client site and this, in addition to config server and some other aspects not mentioned here will alleviate them in good measure.

**Comment by stevehu** [comment]
@ddobrin You have raised several good points. Basically, we want to resolve the properties override in the config files. We have an ad-hoc implementation in ServerConfig for one of the projects that need to overwrite httpPort and httpsPort in server.yml (https://github.com/networknt/light-4j/blob/master/server/src/main/java/com/networknt/server/ServerConfig.java#L55)

Now, it is time to think about generic solutions not only to support Azure app container or cloud foundry, but also to ease the configuration management effort. To have a centralized env_vars.yml is a good idea to allow multiple services to share a set of config templates with only the changed properties extracted out. We also need to give an option to additional override through system properties and environment variables passed into the container. This is not in conflict with config server but actually, make config server much easy to manage. I think a lot of people are focusing on the config server to make it usable. I am wondering if one of you can set up a conference call this week to discuss the implementation details so that we can join the effort together. Thanks.

**Comment by ddobrin** [comment]
Thursday at 11:00 AM or Friday at 10:00 AM.
I do have a conference bridge. Let's agree on time and I send details out individually. 

@stevehu @pragmaticway @NicholasAzar @miklish: let me know.

Note:
- the env_vars.yml can be organizaed by a simple compisite key: <file.key>.
ex.: {audit.enable}. We retrieve config by config file name, therefore making it easy to read automatically the file and resolve it. The "enable" field in audit,yml, if it has an override, can be automatically picked up and resolved.

- my client is preparing a file with all the overrides they need from test phase to test phase, for one API. It is going to be a good representation of many APIs, as it has secrets, datasource, URLs, etc

**Comment by ddobrin** [comment]
I can see that there are not takers for a conf call.

I will propose a prototype based on the above by next week.

**Comment by ddobrin** [comment]
@jiachen1120: 
2 small requests:
1. could you please provide here a sample of usage? 
2. could you please consider an implementation from an environment variables file which is automatically injected at start-up, in lieu of the System.getProeprty approach?

Thank you

**Comment by NicholasAzar** [comment]
Hi @ddobrin, I tend to disagree with the approach of having a separate file to define which fields to inject into default files (if I've understood you're suggestion correctly). This seems to me as solving a separate issue to simply allowing environment variables to be used as part of config.
Although, I would certainly be behind having a single file used to overwrite default values (in the same way you describe), which could be used for environment variables, but not made specifically for them. I think this should be tracked in a different issue.

**Comment by ddobrin** [comment]
@NicholasAzar : there were suggestions, in this trail, as well over email, for a simple call to hash it out.

I have not suggested that a file can not be used for other purposes, however I am suggesting that a file can be used to set any value marked as an env variable. 
It will be directly usable at my client, and they build a high number of APIs.

Alternatively, I support the idea of setting them as command-line env variables and, if even system properties, if somebody finds it useful as such.

I would like us to build a simple, flexible solution where this can be a "no code change" type of improvement to the Config module, which would not require developers to write additional code or having to inject anything, if they can be helped by simple providing a file.

It would help DevOps teams as well

**Comment by stevehu** [comment]
I think both environment variables and an environment file are very similar and they should be implemented in the same way with abstraction the source of the variables to replace the placeholders in the config file templates. If you look at the title of this issue, it only mentioned environment variable but with all the additional info in the discussion, I think we should do both to give more options to inject variables into the configurations. From the implementation perspective, I think we can address both at the same time. @NicholasAzar @ddobrin @jiachen1120  Do you think we can change the title of this issue to reflect both approaches? Thanks.

**Comment by miklish** [comment]
Please examine work done on config file value injection at the following repository (develop@feature-keystores branch).

##### Design
The config tool is built using based on '[clean architecture](http://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html)' and is therefore very amenable to plugin functionality.

##### Roadmap

1. keystore-creation functionality,
2. Web form functionality,
3. Light Config Server Integration / Light Bot Integration.

_**Note**: We have settled on double-curly braces for 'tags' (e.g.: **{{**inject-value-here**}}** ) to allow them to be included in logback.xml files (which already use single curly braces to define log output formatting)._  

We have resources working on the close integration of this tool with Light Config server and we have begun to look into the Light Bot integration as well.

Please inspect the docs in the [develop@feature-keystores](https://github.com/miklish/aotearoa/tree/develop%40feature-keystores) branch to see what functionality it contains that may be of use to you, and what functionality you require that it currently lacks.

##### Note about the AOtearoa repository
The repository ([miklish/aotearoa develop@feature-keystores](https://github.com/miklish/aotearoa/tree/develop%40feature-keystores)) should likely be moved into the networknt org (since this was developed on CIBC time, I'm not sure how appropriate it is to keep it under my personal account).

**Comment by miklish** [comment]
E.g.: By writing a custom implementation of IValueGateway, the tool can immediately pull values from environment variables with almost no other code changes required.

It currently supports pulling values from:

- from command line prompts
- from a value file
- from local web form (close to completion)
- config server (on roadmap / future)

It would be trivial to add 'from environment variables' to this list.

**Comment by NicholasAzar** [comment]
@ddobrin What you suggest you put into a separate file, i suggest we follow a pattern. Your suggestion of having a file identify which fields to replace with environment variables is not what this issue is asking for.

To reiterate, what i can get behind (not what you suggested, but close enough), would be to have a file to selectively override default values with any value (Including environment variables by pattern). I would prefer these to be implemented individually (including separate issues), but if that's unwanted surely it wouldn't be a big deal to group them.

@miklish not ignoring your feedback, just trying to keep the discussion in this thread to runtime/startup configuration processing.

**Comment by ddobrin** [comment]
@NicholasAzar : I am not suggesting that a file identifies values to be replaced.
I am suggesting that you set env variables in the various config files, and that one env_vars.yml "holds" all the variables and their corresponding values.

For easier automation, and ease of reading, my client likes the idea of :
server.yml:
...
buildNumber: ${server.buildNumber:latest}
...

and the env_vars.yml (or whatever name we inject):
...
server.buildNumber: 123
...

At start-up, each time you load a config for a module, you can check (and you inject the class reading the file, or the class setting properties or whatever method) whether an override for values is specified and you get the value.

Say, you check in the map loaded from env_vars.yml, for ex, whether any override data has been provided, and you look up the value.

It is (by convention, of course) easy for people who work on the env_vars.yml to set unique env variables and also to know where the variable originated from.

it is just simple and the Config module handles everything, the API doesn't change anything to support this.

My client has prepared one such file with all the variables they configure when moving from env to env.
That file can be updated for DevOps, whether it is what @miklish is suggesting or another method or the override file exists in a segregated config Github.

**Comment by ddobrin** [comment]
This was all explained from the top of the issue trail

**Comment by NicholasAzar** [comment]
Oh i see, so it seems like what you're suggesting aren't environment variables at all.. this has taken an interesting twist 😄
@stevehu was this your understanding? would love to hear your thoughts!

**Comment by jiachen1120** [comment]
@ddobrin My understanding of your opinion is that when injecting variables, the variables can not only be get directly from the current system(maybe setting by the commend line). It also can be get from a centralized config file which contains all the key-value pairs need been injected. In this way, two devopt way to define these injectable key-value pairs.
1. define them by using commend line
2. define them by add into this centralized config file
Is that correct? Look forward to your response.

@NicholasAzar @stevehu For the implementation, my idea is to read the environment variables from both system and this centralized environment config file and save them into cache. Then, every time I need injection, just check the cache.

**Comment by ddobrin** [comment]
@jiachen1120 : I think that the Config would load configs from the respective config file, whether it is server.yml, service.yml, or many other *.yml files.

When they load, they would check whether the key-value pair has a value marked as ${}. If it does, it would check from a cache, which is a map or another form of collection, whether that values exists. 
The value could be defaulted  or it could be provided as a values to be resolved from this cache.

Now, how do we get this cache?
At load time, we can inject a file, or we can pass the values from the command-line. This in the end is immaterial, yet what is important is that the Config class gets access to the cached values (if they are set) in an identical manner.

We can even provide a file and set the rule that we load the file and then could potentially overwrite it from the command line; this is just as much complexity as we wish to have.

The important thing is that developers of an API would not have to write any code to use this facility.

We can call it environment file or setting environment variables from the command-line, it doesn't matter. It matters that we can inject them in various ways, at start-up, and have a consistent way of resolving them when we load an individual config file.

Developers and DevOps folks have flexibility and teams decide what suits their efforts best.

**Comment by stevehu** [comment]
I am so happy to see that we have reached this level of the details. The original request we opened by @pragmaticway in order to find a solution to deploy light-4j services to CloudFoundry. As the platform manages the port number and it has to pass to the light-4j service, he mentioned the solution would be using system properties/environment variables. Basically, the idea is to inject variables to the light-4j configuration and system property is one of the options. Later, Dan came up an idea to use an env-vars.yml file to inject multiple values when moving from one environment to another. This is another use case than the original one as it is trying to resolve the differences between environments in a deployment pipeline. In essence, both use cases need configuration injection in the Config module. As Dan has described, we could implement both and let environment variable ultimately overwrite the env-vars. This allows us to cover all possible use cases and the implementation can be an abstraction when we construct the cache. 

I think this thread is the best example that we have all the stakeholders to discuss the detailed design. As @jiachen1120 and I have discussed, we should write all the details to the RFC so that other contributors can review and provide feedback before the implementation. 

For new features added to the platform, I would recommend writing an RFC first to encourage further discussions before implementation. Now we have so many projects at different stages and we should be very careful to ensure backward compatibility when adding new features or fixing defects.

**Comment by jiachen1120** [comment]
@NicholasAzar @stevehu I just updated RFC documents, which contains my implementations. The specific code can be examined from https://github.com/jiachen1120/light-4j/tree/develop/config. I look forward to your valuable comments, suggestions for improvement, and more ideas:)

**Comment by jiachen1120** [comment]
https://github.com/jiachen1120/light-4j/tree/develop2/config
This is the code of 0006-config-injection-guidance.md. 

Compared with previous design which provide user more flexibility to manage their config, this design setup the restriction for users that only limited config values which signed by ${} can be modified. the previous design can be checked in https://github.com/jiachen1120/light-4j/tree/develop/config. 

In my opinion, Those two designs can be used in different scenarios. Just like what Dan said yesterday, for those people who don't know the details and just want to config easily, to provide just a list of values which need to be modified would be less confused. However, for some developers who want to change the construction of a config, for example, change a string to a map. The first design would be more helpful. Look forward to your opinion and advise about this two design! @NicholasAzar @ddobrin @chenyan71

**Comment by ddobrin** [comment]
Hi @jiachen1120:
Thank you for posting the MD file on the config 👍 

A small question here, just to confirm my understanding (this is an arbitrary sample):
server.yml:
...
buildNumber: ${server.buildNumber:latest}
...

values.yml:
...
server.buildNumber: 123
...

If the values.yml file is provided, the BuildNumber would be replaced with "123", and if not, then it would use "latest".

Does this sound good?

**Comment by jiachen1120** [comment]
@ddobrin Thanks for your response. Yes, 100% agree with your reply. The design is completely in accordance with the example you mentioned. 

Further extension about your example, 
server.yml:
...
buildNumber: ${server.buildNumber:latest}
...

values.yml:
...
server.buildNumber: 123

environment variables:
...
server.buildNumber=456

1. Both value source exist

If the order code equals to [0]: buildNumber: 123
If the order code equals to [1]: buildNumber: 123
If the order code equals to [2]: buildNumber: 456
If the order code equals not set:buildNumber: 456 (default[2])

2. only environment variable is provided

If the order code equals to [0]: buildNumber: latest
If the order code equals to [1]: buildNumber: 456
If the order code equals to [2]: buildNumber: 456
If the order code equals not set:buildNumber: 456 (default[2])

3. only values.yaml is provided

If the order code equals to [0]: buildNumber: 123
If the order code equals to [1]: buildNumber: 123
If the order code equals to [2]: buildNumber: 123
If the order code equals not set:buildNumber: 123 (default[2])
 
4. Neither environment variable or values.yaml is not provided 

If the order code equals to [0]: buildNumber: latest
If the order code equals to [1]: buildNumber: latest
If the order code equals to [2]: buildNumber: latest
If the order code equals not set:buildNumber: latest (default[2])

Another thing I would like to clarify is that in"${server.buildNumber:latest}", the key's name "server.buildNumber" also can be provided as arbitrary string instead of a exactly path just like 
example. Just make sure this name also exist in environment variable or values.yaml 

In addition, can I add this example you provided to MD?

**Comment by ddobrin** [comment]
@jiachen1120 : feel free to add anything to the example, and your more detailed sample would be a good addition.

I agree that you don't have to use the convention <config file>.<key> (server.buildNumber for ex). You can set anything you want, it was a example.

I'll recommend that naming at my client as they have a lot of APIs and they already have this in place for a number of projects (not necessarily on light-4j). It is simple to understand but you can set anything you wish
