### ISSUE TITLE
original status.yml info in light-4j is overwritten by customer, which will lose errors for light-4j

### ISSUE THREAD

**Issue by BalloonWen** [networknt/light-4j#389]
I notice that when a project has its own status.yml, it overwrites the error code for light-4j.
It will cause a null pointer exception in current code LightHttpHandler.setExchangeStatus()
I think we should provide a way to keep all the info defined in status.yml in the light-4j module.

Related RFC: https://github.com/networknt/light-rfcs/blob/master/light-4j/0015-merge-status.yml-of-light-4j

**Comment by stevehu** [comment]
The default status.yml from Status module in light-4j should not be overwritten as these error messages are used by the platform itself. It has been an issue for a lot of project teams trying to merge the application specific status codes with the platform status codes. The original idea is to use the light-config-server or light-bot to merge them in the pipeline before deployment. I am wondering if we can merge the status.yml from application src/resources/config folder or externalized folder with the default status.yml in the Status module in the Config module. If this works, we can eliminate 90 percent of the issues. For the application developers, they only need to define the application specific code in the status.yml in a specific range. If any conflict occurs during the merge, we need to stop the server and let the user fix the conflicts. This can guarantee applications are not using duplicated error codes that are reserved for the platform. @jiachen1120 @NicholasAzar @ddobrin what do you think?

**Comment by ddobrin** [comment]
@stevehu : this works if there are 2 status.yml files in 2 set locations:
1. one is the light-4j/status module
2. the second is the microservice itself, in its /src/main/resources/config dir

Now, there are APIs which do not follow that pattern, leverage shared statuses and "feed" statuses from:
1. a common location across the enterprise
2. a common location within one domain
3. a common location within one subdomain.

The microservice itself might not declare a status.yml at all

My client is in this mixed situation and light-bot has a mergeStatus specifically for such "concatenation". It weeds out duplicates, of course.

I would say that we can introduce such behaviour, however only if we make it configurable in the config.yml, as well as the light-codegen (which should set that flag or not).
If somebody wishes to do the on-the-fly merge, it is good, if somebody doesn't, and takes it upon himself/herself to provide the status.yml, merged, then the current behaviour (overwrite) is preserved and all is good as well.

Otherwise, the behaviour is not backwards compatible.

@BalloonWen : why don't you add a simple RFC doc for it, for clarity?

**Comment by BalloonWen** [comment]
@ddobrin Hi Dan, I added a breif RFC doc: https://github.com/networknt/light-rfcs/blob/master/light-4j/0015-merge-status.yml-of-light-4j

Let's discuss. @stevehu @NicholasAzar @jiachen1120

**Comment by stevehu** [comment]
@ddobrin I think you have a good point. Make it configurable in the config.yml so that people can choose which approach to go. I think at least 90 percent of users will be covered by this dynamic merging and for big organizations with hierarchical status management, they can still leverage light-bot for the merging. The proposal at least eliminates the painful issue we are facing for now.

**Comment by ddobrin** [comment]
@BalloonWen : this RFC is not approved, and we should not have checked it directly into the master branch of light-rfcs/light-4j.

@stevehu : It covers all scenarios.

@BalloonWen : I would add the flag as : mergeStatus with a default set to false (current behaviour), add a flag to the code gen and document it, as users need to be aware of it

**Comment by stevehu** [comment]
I forgot to lock down the light-rfcs repository and I will do once this RFC is settled. With the new process we have discussed, we need to create the rfc in another branch and open a pull request so that people can discuss the ideas. Once agreed, we can merge the RFC and then create an issue to work on it. The process is still working in progress and it can be accessed at https://doc.networknt.com/contribute/development/ Please let me know if you have questions or have ideas to improve it. It is an ongoing effort and the goal is to ensure the quality of the products, facilitate discussions and not hindering productivity.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [original status.yml info in light-4j is overwritten by customer, which will lose errors for light-4j](https://trello.com/c/PP6qrQDX/103-original-statusyml-info-in-light-4j-is-overwritten-by-customer-which-will-lose-errors-for-light-4j)
