### ISSUE TITLE
Support client provided Scopes for interaction with OAuth

### ISSUE THREAD

**Issue by BalloonWen** [networknt/light-4j#391]
Provide the ability to add scopes manually when getting a client credential token.
Client module:
When a request is issued from the client module to an external service the client should be able to provide a list of scopes to the OAuth server in order to populate the JWT that's returned.
Router:
When a request is made to the router, the request should include the list of scopes required in the request to the OAuth server.

**Comment by stevehu** [comment]
@BalloonWen The change is pretty significant as the existing caching and renew logic in the client module might not be working anymore. Would you be able to write an RFC document so that we can discuss the design? In the RFC, please provide all the use cases so that we can understand the rationale about the change. Thanks.

**Comment by stevehu** [comment]
@BalloonWen As we have discussed, add scopes to the request to the OAuth 2.0 provider might not be practical in microservices architecture. Here is the link to token exchange and it allows the user to just specify the target serviceId instead of scopes. https://datatracker.ietf.org/doc/draft-ietf-oauth-token-exchange/
