### ISSUE TITLE
Shutdownhook not fire on Windows if Light-4j app is killed

### ISSUE THREAD

**Issue by PeterKieu** [networknt/light-4j#392]
For Light-4j (up to version 1.5.28) app running on Windows as WinServiceWrapper (https://github.com/kohsuke/winsw), Windows Service Manager or inside java IDEs (Netbeans, Intellij), the Light-4j app cannot fire Shutdownhook event when it is killed/stopped.

However, when running from command line: java -jar lightApp.jar, then kill by CTRL+C, Shutdownhook is fired smoothly.

Non similar issue found on Linux, Mac.

We should analyze more to improve Windows shutdown/kill signaling mechanism to fix the Light-4j server hook.

**Comment by stevehu** [comment]
@PeterKieu Thanks for bringing it up. Although Windows is not our primary target platform, it is a potential one. I will mark this issue as Help Wanted and hope someone who is familiar with Windows OS to help us to figure out what kind of signal needs to be sent to allow JVM process to clean up gracefully. It is not a high priority issue as I haven't heard anybody using Windows for production yet.

**Comment by lanphan** [comment]
@PeterKieu just some reference documents for you:
1. I don't know much about WinServiceWrapper, but seems yajsw (Yet Another Java Service Wrapper) can capture shutdown hook and setup some config for it, you can refer it here: https://sourceforge.net/p/yajsw/discussion/810311/thread/660e6551/

2. Netbeans, IntelliJ doesn't support it, you have to kill it via command line in order to trigger debug in shutdown hook if any: https://stackoverflow.com/questions/24660408/how-can-i-get-intellij-debugger-to-allow-my-apps-shutdown-hooks-to-run

**Comment by PeterKieu** [comment]
Thanks for your sharing!

**Comment by stevehu** [comment]
@PeterKieu @lanphan Do we still need to put effort on Windows? Some users are just using this platform for development and the target production environment is always Linux or Linux container. It is nice to have in my opinion.

**Comment by PeterKieu** [comment]
@stevehu On Windows, this issue caused by Netbeans debugger (8.x, 10.x, 11.x). I think that new Windows service wrappers for Java app will run well in Windows production environment.
Thus, no need to put more effort on this issue. The problem is due to process-killing mechanism by Netbeans or other Java IDEs.
@To whom may concern: Don't kill Light-4j app by Netbeans IDE, just use Windows task manager or Ctrl+C in Cmd/PowerShell.

**Comment by stevehu** [comment]
@PeterKieu Thanks a lot for the investigation and confirmation. I am going to close this issue then.
