### ISSUE TITLE
Error happen if there is not value in values.yml for services.yml injection

### ISSUE THREAD

**Issue by chenyan71** [networknt/light-4j#407]
Light-codegen (after 1.5.30) will generate service.yml as below:

```service.yml
### Singleton service factory configuration/IoC injection
singletons: ${service.singletons}

```

And in the values.yml, we can add value injection for the service.yml. But if there is not value need be set for services.yml. For example:

```values.yml
service.singletons:
# StartupHookProvider implementations, there are one to many and they are called in the same sequence defined.
# - com.networknt.server.StartupHookProvider:
  # If you are using mask module to remove sensitive info before logging, uncomment the following line.
  # - com.networknt.server.JsonPathStartupHookProvider
  # - com.networknt.server.Test1StartupHook
  # - com.networknt.server.Test2StartupHook
```
The system will get error when we start service:

Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.networknt.server.Server.start(Server.java:143)
	at com.networknt.server.Server.init(Server.java:128)
	at com.networknt.server.Server.main(Server.java:115)
Caused by: com.networknt.config.ConfigException: "${service.singletons}" appears in config file cannot be expanded
	at com.networknt.config.ConfigInjection.getInjectValue(ConfigInjection.java:56)

But if we set some values in the values.yml, then it works fine:

```values.yml
service.singletons:
- com.networknt.balance.LoadBalance:
  - com.networknt.balance.RoundRobinLoadBalance
- com.networknt.cluster.Cluster:
  - com.networknt.cluster.LightCluster
```

**Comment by stevehu** [comment]
@chenyan71 It looks like there is only a key without a value. We need to try something like an empty string to see if it works. @jiachen1120 is looking into it as well. Please have a chat with him to find the best solution. Thanks.

**Comment by ddobrin** [comment]
It works without setting a value:

### Singleton service factory configuration/IoC injection
singletons:

I am using it as such in service.yml at my client.
The issue can arise if you leave maps/arrays generation on in the codegen, however this can easily be bypassed

**Comment by jiachen1120** [comment]
Good morning! @chenyan71 @stevehu @ddobrin 

I tried returning an empty string and null for upper case provided by @chenyan71 . I found that an empty string would lead to an exception since the service module cannot parse the empty string. But `null` can pass normally.

The improved performance is as follows:

1. If can't get the value from either environment variables, default values, or values.yml. but values.yml contains the corresponding key, return `null`.

This improvement allows users to set null in values.yml. 
https://github.com/networknt/light-4j/pull/409

**Comment by jiachen1120** [comment]
For @chenyan71 's case. Other issues would be raised if the service cannot found instance in the service map. For example:

HOST IP null
Failed to register service, the server stopped.
11:21:20.009 [main] training.customers-1.00.00  ERROR com.networknt.server.Server init - Server is not operational! Failed with exception
java.lang.RuntimeException: Could not find registry instance in service map
	at com.networknt.server.Server.bind(Server.java:277)
	at com.networknt.server.Server.start(Server.java:170)
	at com.networknt.server.Server.init(Server.java:128)
	at com.networknt.server.Server.main(Server.java:115)

**Comment by stevehu** [comment]
@jiachen1120 The above error is due to the configuration mismatch between server.yml and service.yml. In the server.yml it is set registry as true but there is no corresponding implementation is configured in the service.yml file. As long as we have a clear error message shown up, I think we are OK.

**Comment by chenyan71** [comment]
@jiachen1120 The change you had works  for me. And agree with Steve, the issue you mentioned above shouldn't be problem.

**Comment by jiachen1120** [comment]
@chenyan71 @stevehu I know. just pointed out to prevent ambiguity :)
