### ISSUE TITLE
Retrieve symmetric key for config decryption

### ISSUE THREAD

**Issue by jiachen1120** [networknt/light-4j#427]
@dz-1 has already implemented Integrate decryption module in all retrievals of config https://github.com/networknt/light-4j/issues/413

But the symmetric key is hard coded as framework name "light" in AESDecryptor. We need to make it configurable

processes need to be defined:
Deployed in VM:
Key retrieved by user input on server start
Deployed in CaaS:
Key retrieved by environment variable

**Comment by stevehu** [comment]
The best way to make it work is through [light-config-server](https://doc.networknt.com/service/config/) as it defines a process to split the key between the service owner and the DevOps engineer. No single person knows the key in full but the config server and service instance knows the full key to enable the encryption and decryption.

**Comment by jiachen1120** [comment]
@stevehu Hey. I think this requirement might apply to users who don't want to use the config server. In the absence of a config server, perhaps relying solely on config modules can lead to potential security issues? Since the password for decryption is fixed

**Comment by jiachen1120** [comment]
@stevehu Also would like to ask you a question about the config server, Is the config got from config server is decrypted?

**Comment by stevehu** [comment]
@jiachen1120 I agree that we need to have a solution for standalone applications; however, it would be very hard to just use the environment variable and we need a way to get the key inside the application itself. If you have some ideas already, please write an RFC so that we can discuss. 

When using the config server, the values should be encrypted by the config server and decrypted in the application. The key in the application is constructed by something set up in the application and an environment variable provided by the DevOps engineer.
