### ISSUE TITLE
Cache unparsed request body (configurable)

### ISSUE THREAD

**Issue by ddobrin** [networknt/light-4j#437]
The BodyHandler (light-4j/body) currently parses the body of the request and caches the parsed body as an attachment in REQUEST_BODY.

There are use cases when the "unparsed" body is useful for some operations and avoids a serialization effort.

The body.yml needs to be augmented with a property, with a default value set to "false".
Teams which will use it will set it to true as per their use case.
...# Enable body parse flag
enabled: true
...# cache request body
cacheRequestBody: false

The BodyHandler would have to be augmented and should save, if the above flag is set to true, the unparsed body as a String, as an attachment in REQUEST_BODY_STRING.

NOTE: light-codegen already parameterizes the body.yml at this time, therefore no changes are required in the codegen utility

**Comment by jiachen1120** [comment]
Hey! @ddobri @stevehu I encounter a problem when trying to implement caching unparsed request body when the content type is "multipart/form-data" and look forward to your helps.  

Due to the extended problem of undertow, the only way to parse the form-data is using the method formParserFactory.createParser(exchange), which means we need to reuse the input stream inside the undertow exchange. However, the undertowInputStream didn't override the reset() method and cannot be reused. So, after caching the unparsed body from the undertowInputStream, we cannot parse the body from the exchange again since the input stream already closed. 

It seems the only way to solve it is to write an ourselves form-data parser. Do we need to do that? Or, just implement the caching for Json format? Since I think there is nearly no use cases for unparsed form-data body.

**Comment by ddobrin** [comment]
@jiachen1120 : If you consider that this issue can not easily be addressed, then writing an additional parser is not warranted.
There are a couple of use-cases for it, at least the ones which I am aware of.

Please reassign the issue to me and I will close it in the next few days, after investigating a couple of different ideas. 
You can label it as "to be analyzed" or something you see fit

**Comment by stevehu** [comment]
@ddobrin @jiachen1120 I guess the use cases you are talking about are for JSON only. In my opinion, there is no need to keep the original string for form-data as there is no original string at all. As our body parser differentiate body with the content type, we can just keep the original string for the `application/json`. What do you think?

**Comment by jiachen1120** [comment]
@stevehu @ddobrin Thanks for your help!!!

I just created a PR which included: 
1. implementation of caching application/json request body string
2. refactored the bodyHanlder
3. test cases

I agree @stevehu opinion that there is no need to keep the original string for form-data as there is no original string.
