### ISSUE TITLE
Consul TTL check "checkPass" issue

### ISSUE THREAD

**Issue by BalloonWen** [networknt/light-4j#458]
-When Consul has multiple instances, light-consul will send health check actively. Whenever the connection redirects to another instance of Consul, it will checkPass fail.
-We're still confirming if this is a consul serverside issue.
-Light-4j may have workarounds for this problem such as caching the connection host when first connected, or whitelist Consul so that it can use "httpcheck", we need to discuss.
> Hi Steve,
> As discussed, Consul registry failed with 2 pods. Please find the stacktrace and consul.yml file below.
> This issue can be simulated in Openshift container. Thanks
> 
> **Exception stackTrace:**
> 
> ```
> [2019-03-29@17:05:31.753][ERROR][][][][pool-3-thread-3][c.n.consul.client.ConsulClientImpl.checkPass:113] - CheckPass request exception
> java.lang.Exception: Failed to checkPass on Consul: 500:Unknown check "service:*.*.*.*:com.example.api1-1.0.0:15211"
> 	at com.networknt.consul.client.ConsulClientImpl.checkPass(ConsulClientImpl.java:110)
> 	at com.networknt.consul.ConsulHeartbeatManager$HeartbeatJob.run(ConsulHeartbeatManager.java:173)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> ```
> **Consul.yml file:**
> 
> ```
> consulUrl: http://consul.example.com:8500
> deregisterAfter: 1m
> checkInterval: 10s
> tcpCheck: false
> httpCheck: false
> ttlCheck: true
> ```

**Comment by stevehu** [comment]
While discussing with HashiCorp support guys, they recommend implementing a cluster of servers three or five nodes and a list of agents. All microservices should talk to an agent instead of a cluster node. My understanding is that your service is connecting to Consul with a round-robin DNS so different requests might go to a different Consul node. One suggestion would be to pin all your service instances to a particular node with the IP address instead of DNS. 

The other approach is to use the httpCheck which is more reliable than ttlCheck; however, there is an issue with two-way TLS and we need to figure out how to bypass the host verification from the Consul.

**Comment by BalloonWen** [comment]
Closed because it was a Consul issue. It's recommended to connect to Consul using Consul agent in each node.

**Comment by miklish** [comment]
FYI: I will add that, based on testing with my employer, this issue still exists even when using the Consul agent. So it does not appear to be related to connections to multiple nodes in a Consul cluster.
