### ISSUE TITLE
Configure dependabot on project

### ISSUE THREAD

**Issue by jefperito** [networknt/light-4j#520]
Guys, what do you think about dependabot?

https://github.com/marketplace/dependabot-preview

**Comment by stevehu** [comment]
@jefperito We are using part of the services for daily notifications and using light-bot to update all the repositories in one shot. I have tried to enable it on light-example-4j but given up due to too many permissions asked. Do you have any experience with this tool? how do you like it?

**Comment by ddobrin** [comment]
How would it address the licensing issues, in case an update would introduce any issues ?

**Comment by stevehu** [comment]
For an open source project, it is unlikely to change the license; however, I do see some cases that license has been changed for the new version. When we are using light-bot to upgrade certain dependencies, I have to review the release notes of the new version to ensure the backward compatibility and license agreement. These days, we are constantly reviewing the licenses of dependencies because we are providing indemnification for our customers.

**Comment by jefperito** [comment]
@stevehu i don't have experience with that tool, but i've read some articles about it and seems promising, Github aquired and now dispose for free

**Comment by jefperito** [comment]
closing this question because it's no longer needed because seems it been used here: https://github.com/networknt/light-example-4j/pull/107

**Comment by stevehu** [comment]
@jefperito Yes. I am trying to use it in the light-example-4j. I don't know when it will send a PR and still in the process to learn it. We might set it up with other repositories once we are comfortable with the tool. Thanks a lot for introducing it.
