### ISSUE TITLE
implement a connection pool for Http2Client in case the server is HTTP/1.1

### ISSUE THREAD

**Issue by stevehu** [networknt/light-4j#572]
HTTP/2 support multiplex and we can use one connection to send multiple concurrent requests. However, if the server doesn't support HTTP/2, then the connection will be downgraded to the HTTP/1.1 and we need a connection pool to allocate one connection per request.

**Comment by jiachen1120** [comment]
@stevehu 
Through the investigation, I found that whenever the method `getRequestService()` inside http2client is called, regardless of whether  enable http2 or not, a new connection will be established. The connection type will be http2ClientConnection or httpClientConnection, depending on whether the target server supports http2. So for the current http2client, the type of connection does not affect the functionality.

I think maybe we should build a connection pool for http2connection based on host instead of create one for http/1.1. This avoids creating multiple http2connections for the same host. And for httpConnection. Each request to establish a new connection may be able to avoid blocking the connection as much as possible. (I think the scenario is different from consul)

**Comment by ddobrin** [comment]
At my client, we had this issue and it was a showstopper.

We introduced an (older) REST client and used that one to connect to the downstream service.

**Comment by jiachen1120** [comment]
@ddobrin Hello, Dan! Could you please specify the use cases of http2client for that showstopper? Have you use the `getRequestService()` method or using `connection.sendRequest()` to call the downstream service? That would be very helpful! Thanks!

**Comment by stevehu** [comment]
@jiachen1120 getRequestService is a new API added for the circuit breaker and completable future. You are right that it creates a new connection every time it is called. I think we can refactor it to share the same connection if possible. @chenyan71 @yibogithub @jefperito What do you think?

I like the idea to associate the connection pool with the host regardless of HTTP/1.1 or HTTP/2. Once the connection is created, we can create multiple instances (HTTP/1.1) or single instance (HTTP/2). 

@ddobrin I remember that you mentioned that by specifying http2 does not guarantee the connection created is HTTP/2 and you have a workaround. Could you please elaborate the details?

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [implement a connection pool for Http2Client in case the server is HTTP/1.1](https://trello.com/c/tXzEEDM9/402-implement-a-connection-pool-for-http2client-in-case-the-server-is-http-11)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [implement a connection pool for Http2Client in case the server is HTTP/1.1 master](https://trello.com/c/gtvN6BoI/403-implement-a-connection-pool-for-http2client-in-case-the-server-is-http-11-master)
