### ISSUE TITLE
when all instances are down and restarted, the client discovery might not triggered

### ISSUE THREAD

**Issue by stevehu** [networknt/light-4j#579]
The following is the sequence:

A consumer service calling a provider service and all providers are down. 
The serviceToUrl returns null in the consumer service. 
Consume service keeps retrying...
Provider service is up with one or more instances. 
The consumer service might not discover the newly started provider service instances. 

We need to remove the cache in the service map before return null in the second step above to force the discovery in the last step.

**Comment by ddobrin** [comment]
At the time the host could not be found, the code returns null: this is simple and elegant

   public String serviceToUrl(String protocol, String serviceId, String tag, String requestKey) {
        URL url = loadBalance.select(discovery(protocol, serviceId, tag), requestKey);
        if (url != null) {
            return protocol + "://" + url.getHost() + ":" + url.getPort();
        } else {
            return null;
        }

At this time, the serviceMap:
private static Map<String, List<URL>> serviceMap = new ConcurrentHashMap<>();
will still contain the list of URLs for the service ID.

Change#1: we need to invalidate the serviceMap with a remove(), forcing the next discovery to refresh.

Long-term, unused services, say over 30s, will be refreshed by the fix for issue #577.

Change#2:
The discovery() method gets the values from the serviceMap and checks for null.
This is good if the serviceID can't be found, however, if it is reset, ConcurrentHashMap can't have nulls, therefore we need to add a check for the empy ArrayList:

        List<URL> urls = serviceMap.get(serviceId);
        if(logger.isDebugEnabled()) logger.debug("cached serviceId " + serviceId + " urls = " + urls);
        if(urls == null) {
to
      if((urls==null) || (urls.isEmpty()).

Rationale:
the notify() method would set an empty map:
public void notify(URL registryUrl, List<URL> urls) {
            logger.debug("registryUrl is: {}", registryUrl);
            logger.debug("notify service: {} with updated urls: {}", serviceId, urls.toString());
            if(StringUtils.isNotBlank(serviceId)) {
                serviceMap.put(serviceId, urls == null ? new ArrayList<>() : urls);
            }

**Comment by stevehu** [comment]
Makes sense. I have made the suggested change. Please review. Thanks.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [when all instances are down and restarted, the client discovery might not triggered](https://trello.com/c/uByDvU6S/331-when-all-instances-are-down-and-restarted-the-client-discovery-might-not-triggered)

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [when all instances are down and restarted, the client discovery might not triggered](https://trello.com/c/a4KqZjmX/332-when-all-instances-are-down-and-restarted-the-client-discovery-might-not-triggered)
