### ISSUE TITLE
Interface with multiple generic type parameters not supported

### ISSUE THREAD

**Issue by shuchigupta** [networknt/light-4j#635]
I'm having trouble injecting a class from framework which has multiple generic type parameters, eg.

public interface A<T, U> {
    U doSomething(T request);
}

public class AImpl implements A<Request, Response> {
     Repsonse doSomething(Request request) {
          .......
     }
}

My service.yml looks like this:

- com.A<com.request.Request, com.response.Response>:
   - com.impl.AImpl

However, SingletonServiceFactory does not have any method to inject class having multiple type parameters:
A aImpl = SingletonServiceFactory.getBean(A.class, Request.Class, Response.class)

**Comment by stevehu** [comment]
@shuchigupta I have added a new test case to the service module and here is my observation and understanding. 

First, the generics are not useful if we are using a reflection-based dependency injection. The injection happens in runtime and type parameters are all Object types. The generic is a way to allow Java compiler to detect errors during the compile time. 

Second, we do have an issue that the interface doesn't support two or more type parameters because the comma is used as a divider for two interfaces. It should be easy to figure out if the comma is within `<` and `>`. The question is should we support it or not given the above reason. 

I have submitted a PR with a test case. Could you please review and let me know what do you think? We can use this issue to discuss what is the next step.
