### ISSUE TITLE
Support Eureka for service discovery

### ISSUE THREAD

**Issue by tsuilouis** [networknt/light-4j#768]
Currently, light-4j has support for Consul and Zookeeper for service discovery. @chenyan71 has stated that the team plans to add a module for Eureka as well. I've expressed interest in taking on this task.

This issue is to track the planning and design of supporting Eureka.

The first step for me should probably be to go through Eureka documentation and figure out how it works at a high level. Then I can look at what pieces are necessary for light-4j to use.

**Comment by stevehu** [comment]
@tsuilouis @chenyan71 Just FYI. I recently created a Portal Registry to replace Consul as it has some issues. Also, a new module portal-registry is added to the light-4j as another registry/discovery support. 

It is a lot simple than Consul and using WebSocket to update instead of Blocking Query(long poll) and it saves a lot of threads for the consumer if there are too many downstream services. 

The long term is to move all users to the light-portal registry that is integrated with a lot of other portal services. I am writing some tutorials and will give you guys access once it is ready.

**Comment by stevehu** [comment]
@tsuilouis @chenyan71 As our strategy is to attract users to use the light-controller along with the light-router, we should focus our effort on the light-portal instead in my opinion. The eureka project is a very good reference for us to implement the light-controller though. What do you think?

**Comment by tsuilouis** [comment]
@stevehu sure, that makes sense. Should I close this issue then? cc @chenyan71

**Comment by stevehu** [comment]
@tsuilouis As we've discussed, I am closing it.
