### ISSUE TITLE
Any support for http2?

### ISSUE THREAD

**Issue by netroby** [networknt/light-4j#86]
Hello, wonder to know does light 4j support http2 server side programming?

**Comment by stevehu** [comment]
Yes. Http2 is supported on the server side by default. Http2 client is working in progress.

**Comment by stevehu** [comment]
In the last several days, I have been busy working on the [Http2Client](https://github.com/networknt/light-4j/blob/develop/client/src/main/java/com/networknt/client/Http2Client.java) and its test case. The code can be accessed in develop branch now and will be merged to master before next release. In order to make sure both server and client work together flawlessly, we need to upgrade to the latest Undertow 1.4.18.Final. Thanks.

**Comment by stevehu** [comment]
Given now we have a client module that support HTTP 2.0 over both TLS and non-TLS, the default config for server have enableHttps=true.
